### ISSUE TITLE
Problema con Prestashop 1.7.4.3

### ISSUE THREAD

**Issue by hfierro** [TransbankDevelopers/transbank-plugin-prestashop-webpay#18] opened 2018-12-18 12:52 UTC
Estimados, gracias por el módulo, pero en 1.7.4.3 tengo el siguiente problema (estoy usando la última versión):

(1/1) ContextErrorExceptionNotice: Undefined index: tpl_dir
--
in bfef76c77571de1a6cd2e9e4801e1472f4ee8b54_2.module.webpayviewstemplatesfront.php line 29
at content_5c18e9880e8e60_63374184(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 206
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, 'layouts/layout-full-width.tpl', null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch('module:webpay/views/templates/front/payment_execution.tpl', null, 'layouts/layout-full-width.tpl', null, false, true, false)in SmartyDev.php line 41
at SmartyDev->fetch('module:webpay/views/templates/front/payment_execution.tpl', null, 'layouts/layout-full-width.tpl')in FrontController.php line 679
at FrontControllerCore->smartyOutputContent('module:webpay/views/templates/front/payment_execution.tpl')in FrontController.php line 663
at FrontControllerCore->display()in Controller.php line 275
at ControllerCore->run()in Dispatcher.php line 428
at DispatcherCore->dispatch()in index.php line 28

**Comment by rbustos** [comment] 2018-12-29 21:09
Que versión de webpay estás usando? creo que esto fue corregido en la versión 3.0.10 
Duplicate of 9#

**Comment by a1b4** [comment] 2019-05-15 14:00
Hola, como menciona @rbustos esto ya se encuentra solucionado en la versión 3.0.10 o superior.

**Closed as completed** 2019-05-15 14:00 UTC
Labels: bug, duplicate
